import * as fs from "node:fs";
import * as path from "node:path";
import * as ngrok from "ngrok";

(async (): Promise<void> => {
	console.log("🌍 Starting ngrok ...");

	const url: string = await ngrok.connect({
		addr: 3000,
		authtoken: process.env.NGROK_AUTH_TOKEN, // Optional if you've already authed locally
	});

	console.log("🌍 ngrok URL:", url);

	const frontendPath: string = path.resolve(
		__dirname,
		"../../app/src/constants/localBackendUrl.ts",
	);
	const content: string = `// This file is automatically generated by the tunnel script
// It will be ignored by git (added to .gitignore)
export const backendUrl = "${url}";\n`;

	fs.writeFileSync(frontendPath, content, "utf8");
	console.log("✅ Updated localBackendUrl.ts");

	// Keep the tunnel open
})();
