steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/personal-projects-456407/audio-stream-service",
        "./audio-stream-service",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/personal-projects-456407/audio-stream-service"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "audio-stream-service"
      - "--image=gcr.io/personal-projects-456407/audio-stream-service"
      - "--platform=managed"
      - "--region=europe-west4"
      - "--allow-unauthenticated"

images:
  - "gcr.io/personal-projects-456407/audio-stream-service"

options:
  logging: CLOUD_LOGGING_ONLY
